local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 

-- ----- 
--  BORDER 
-- ---- 

-- -----
--   FONT
-- -----

-- -----
--   SOUND
-- -----
LSM:Register("sound", "|cFFFF80001|r", [[Interface\Addons\SharedMedia_Alerts\sound\1.ogg]]) 
LSM:Register("sound", "|cFFFF80002|r", [[Interface\Addons\SharedMedia_Alerts\sound\2.ogg]]) 
LSM:Register("sound", "|cFFFF80003|r", [[Interface\Addons\SharedMedia_Alerts\sound\3.ogg]]) 
LSM:Register("sound", "|cFFFF80004|r", [[Interface\Addons\SharedMedia_Alerts\sound\4.ogg]]) 
LSM:Register("sound", "|cFFFF80005|r", [[Interface\Addons\SharedMedia_Alerts\sound\5.ogg]]) 
LSM:Register("sound", "|cFFFF80006|r", [[Interface\Addons\SharedMedia_Alerts\sound\6.ogg]]) 
LSM:Register("sound", "|cFFFF80007|r", [[Interface\Addons\SharedMedia_Alerts\sound\7.ogg]]) 
LSM:Register("sound", "|cFFFF80008|r", [[Interface\Addons\SharedMedia_Alerts\sound\8.ogg]]) 
LSM:Register("sound", "|cFFFF80009|r", [[Interface\Addons\SharedMedia_Alerts\sound\9.ogg]]) 
LSM:Register("sound", "|cFFFF800010|r", [[Interface\Addons\SharedMedia_Alerts\sound\10.ogg]]) 
LSM:Register("sound", "|cFFFF8000Absorb|r", [[Interface\Addons\SharedMedia_Alerts\sound\Absorb.ogg]]) 
LSM:Register("sound", "|cFFFF8000Add|r", [[Interface\Addons\SharedMedia_Alerts\sound\Add.ogg]]) 
LSM:Register("sound", "|cFFFF8000Adds|r", [[Interface\Addons\SharedMedia_Alerts\sound\Adds.ogg]]) 
LSM:Register("sound", "|cFFFF8000Affix|r", [[Interface\Addons\SharedMedia_Alerts\sound\Affix.ogg]]) 
LSM:Register("sound", "|cFFFF8000AoE|r", [[Interface\Addons\SharedMedia_Alerts\sound\AoE.ogg]]) 
LSM:Register("sound", "|cFFFF8000Assist|r", [[Interface\Addons\SharedMedia_Alerts\sound\Assist.ogg]]) 
LSM:Register("sound", "|cFFFF8000Attention|r", [[Interface\Addons\SharedMedia_Alerts\sound\Attention.ogg]]) 
LSM:Register("sound", "|cFFFF8000Avoid|r", [[Interface\Addons\SharedMedia_Alerts\sound\Avoid.ogg]]) 
LSM:Register("sound", "|cFFFF8000Back|r", [[Interface\Addons\SharedMedia_Alerts\sound\Back.ogg]]) 
LSM:Register("sound", "|cFFFF8000Bait|r", [[Interface\Addons\SharedMedia_Alerts\sound\Bait.ogg]]) 
LSM:Register("sound", "|cFFFF8000Bloodlust|r", [[Interface\Addons\SharedMedia_Alerts\sound\Bloodlust.ogg]]) 
LSM:Register("sound", "|cFFFF8000Boss|r", [[Interface\Addons\SharedMedia_Alerts\sound\Boss.ogg]]) 
LSM:Register("sound", "|cFFFF8000Bottom|r", [[Interface\Addons\SharedMedia_Alerts\sound\Bottom.ogg]]) 
LSM:Register("sound", "|cFFFF8000Break|r", [[Interface\Addons\SharedMedia_Alerts\sound\Break.ogg]]) 
LSM:Register("sound", "|cFFFF8000Buff|r", [[Interface\Addons\SharedMedia_Alerts\sound\Buff.ogg]]) 
LSM:Register("sound", "|cFFFF8000CC|r", [[Interface\Addons\SharedMedia_Alerts\sound\CC.ogg]]) 
LSM:Register("sound", "|cFFFF8000CD|r", [[Interface\Addons\SharedMedia_Alerts\sound\CD.ogg]]) 
LSM:Register("sound", "|cFFFF8000Center|r", [[Interface\Addons\SharedMedia_Alerts\sound\Center.ogg]]) 
LSM:Register("sound", "|cFFFF8000Chain|r", [[Interface\Addons\SharedMedia_Alerts\sound\Chain.ogg]]) 
LSM:Register("sound", "|cFFFF8000Charge|r", [[Interface\Addons\SharedMedia_Alerts\sound\Charge.ogg]]) 
LSM:Register("sound", "|cFFFF8000Circle|r", [[Interface\Addons\SharedMedia_Alerts\sound\Circle.ogg]]) 
LSM:Register("sound", "|cFFFF8000Clear|r", [[Interface\Addons\SharedMedia_Alerts\sound\Clear.ogg]]) 
LSM:Register("sound", "|cFFFF8000Collect|r", [[Interface\Addons\SharedMedia_Alerts\sound\Collect.ogg]]) 
LSM:Register("sound", "|cFFFF8000Cross|r", [[Interface\Addons\SharedMedia_Alerts\sound\Cross.ogg]]) 
LSM:Register("sound", "|cFFFF8000Curse|r", [[Interface\Addons\SharedMedia_Alerts\sound\Curse.ogg]]) 
LSM:Register("sound", "|cFFFF8000Dance|r", [[Interface\Addons\SharedMedia_Alerts\sound\Dance.ogg]]) 
LSM:Register("sound", "|cFFFF8000Dead|r", [[Interface\Addons\SharedMedia_Alerts\sound\Dead.ogg]]) 
LSM:Register("sound", "|cFFFF8000Debuff|r", [[Interface\Addons\SharedMedia_Alerts\sound\Debuff.ogg]]) 
LSM:Register("sound", "|cFFFF8000Defensive|r", [[Interface\Addons\SharedMedia_Alerts\sound\Defensive.ogg]]) 
LSM:Register("sound", "|cFFFF8000Diamond|r", [[Interface\Addons\SharedMedia_Alerts\sound\Diamond.ogg]]) 
LSM:Register("sound", "|cFFFF8000Disease|r", [[Interface\Addons\SharedMedia_Alerts\sound\Disease.ogg]]) 
LSM:Register("sound", "|cFFFF8000Disorient|r", [[Interface\Addons\SharedMedia_Alerts\sound\Disorient.ogg]]) 
LSM:Register("sound", "|cFFFF8000Dispell|r", [[Interface\Addons\SharedMedia_Alerts\sound\Dispell.ogg]]) 
LSM:Register("sound", "|cFFFF8000Dodge|r", [[Interface\Addons\SharedMedia_Alerts\sound\Dodge.ogg]]) 
LSM:Register("sound", "|cFFFF8000Dont Move|r", [[Interface\Addons\SharedMedia_Alerts\sound\DontMove.ogg]]) 
LSM:Register("sound", "|cFFFF8000DoT|r", [[Interface\Addons\SharedMedia_Alerts\sound\DoT.ogg]]) 
LSM:Register("sound", "|cFFFF8000Down|r", [[Interface\Addons\SharedMedia_Alerts\sound\Down.ogg]]) 
LSM:Register("sound", "|cFFFF8000DPS|r", [[Interface\Addons\SharedMedia_Alerts\sound\DPS.ogg]]) 
LSM:Register("sound", "|cFFFF8000DPS CD|r", [[Interface\Addons\SharedMedia_Alerts\sound\DPSCD.ogg]]) 
LSM:Register("sound", "|cFFFF8000DR|r", [[Interface\Addons\SharedMedia_Alerts\sound\DR.ogg]]) 
LSM:Register("sound", "|cFFFF8000Drop|r", [[Interface\Addons\SharedMedia_Alerts\sound\Drop.ogg]]) 
LSM:Register("sound", "|cFFFF8000East|r", [[Interface\Addons\SharedMedia_Alerts\sound\East.ogg]]) 
LSM:Register("sound", "|cFFFF8000Enter|r", [[Interface\Addons\SharedMedia_Alerts\sound\Enter.ogg]]) 
LSM:Register("sound", "|cFFFF8000Escort|r", [[Interface\Addons\SharedMedia_Alerts\sound\Escort.ogg]]) 
LSM:Register("sound", "|cFFFF8000Exit|r", [[Interface\Addons\SharedMedia_Alerts\sound\Exit.ogg]]) 
LSM:Register("sound", "|cFFFF8000External|r", [[Interface\Addons\SharedMedia_Alerts\sound\External.ogg]]) 
LSM:Register("sound", "|cFFFF8000Fast|r", [[Interface\Addons\SharedMedia_Alerts\sound\Fast.ogg]]) 
LSM:Register("sound", "|cFFFF8000Fear|r", [[Interface\Addons\SharedMedia_Alerts\sound\Fear.ogg]]) 
LSM:Register("sound", "|cFFFF8000Fixate|r", [[Interface\Addons\SharedMedia_Alerts\sound\Fixate.ogg]]) 
LSM:Register("sound", "|cFFFF8000Focus|r", [[Interface\Addons\SharedMedia_Alerts\sound\Focus.ogg]]) 
LSM:Register("sound", "|cFFFF8000Front|r", [[Interface\Addons\SharedMedia_Alerts\sound\Front.ogg]]) 
LSM:Register("sound", "|cFFFF8000Frontal|r", [[Interface\Addons\SharedMedia_Alerts\sound\Frontal.ogg]]) 
LSM:Register("sound", "|cFFFF8000Gather|r", [[Interface\Addons\SharedMedia_Alerts\sound\Gather.ogg]]) 
LSM:Register("sound", "|cFFFF8000Go|r", [[Interface\Addons\SharedMedia_Alerts\sound\Go.ogg]]) 
LSM:Register("sound", "|cFFFF8000Heal CD|r", [[Interface\Addons\SharedMedia_Alerts\sound\HealCD.ogg]]) 
LSM:Register("sound", "|cFFFF8000Heal to Full|r", [[Interface\Addons\SharedMedia_Alerts\sound\HealToFull.ogg]]) 
LSM:Register("sound", "|cFFFF8000Hide|r", [[Interface\Addons\SharedMedia_Alerts\sound\Hide.ogg]]) 
LSM:Register("sound", "|cFFFF8000High Energy|r", [[Interface\Addons\SharedMedia_Alerts\sound\HighEnergy.ogg]]) 
LSM:Register("sound", "|cFFFF8000High Stacks|r", [[Interface\Addons\SharedMedia_Alerts\sound\HighStacks.ogg]]) 
LSM:Register("sound", "|cFFFF8000HoT|r", [[Interface\Addons\SharedMedia_Alerts\sound\HoT.ogg]]) 
LSM:Register("sound", "|cFFFF8000Immunity|r", [[Interface\Addons\SharedMedia_Alerts\sound\Immunity.ogg]]) 
LSM:Register("sound", "|cFFFF8000In|r", [[Interface\Addons\SharedMedia_Alerts\sound\In.ogg]]) 
LSM:Register("sound", "|cFFFF8000Innervate|r", [[Interface\Addons\SharedMedia_Alerts\sound\Innervate.ogg]]) 
LSM:Register("sound", "|cFFFF8000Intermission|r", [[Interface\Addons\SharedMedia_Alerts\sound\Intermission.ogg]]) 
LSM:Register("sound", "|cFFFF8000Invisibility|r", [[Interface\Addons\SharedMedia_Alerts\sound\Invisibility.ogg]]) 
LSM:Register("sound", "|cFFFF8000Jump|r", [[Interface\Addons\SharedMedia_Alerts\sound\Jump.ogg]]) 
LSM:Register("sound", "|cFFFF8000Kick|r", [[Interface\Addons\SharedMedia_Alerts\sound\Kick.ogg]]) 
LSM:Register("sound", "|cFFFF8000Kite|r", [[Interface\Addons\SharedMedia_Alerts\sound\Kite.ogg]]) 
LSM:Register("sound", "|cFFFF8000Knock|r", [[Interface\Addons\SharedMedia_Alerts\sound\Knock.ogg]]) 
LSM:Register("sound", "|cFFFF8000Left|r", [[Interface\Addons\SharedMedia_Alerts\sound\Left.ogg]]) 
LSM:Register("sound", "|cFFFF8000LoS|r", [[Interface\Addons\SharedMedia_Alerts\sound\LoS.ogg]]) 
LSM:Register("sound", "|cFFFF8000Low HP|r", [[Interface\Addons\SharedMedia_Alerts\sound\LowHP.ogg]]) 
LSM:Register("sound", "|cFFFF8000Low MP|r", [[Interface\Addons\SharedMedia_Alerts\sound\LowMP.ogg]]) 
LSM:Register("sound", "|cFFFF8000Macro|r", [[Interface\Addons\SharedMedia_Alerts\sound\Macro.ogg]]) 
LSM:Register("sound", "|cFFFF8000Magic|r", [[Interface\Addons\SharedMedia_Alerts\sound\Magic.ogg]]) 
LSM:Register("sound", "|cFFFF8000Melee|r", [[Interface\Addons\SharedMedia_Alerts\sound\Melee.ogg]]) 
LSM:Register("sound", "|cFFFF8000Middle|r", [[Interface\Addons\SharedMedia_Alerts\sound\Middle.ogg]]) 
LSM:Register("sound", "|cFFFF8000Mirror|r", [[Interface\Addons\SharedMedia_Alerts\sound\Mirror.ogg]]) 
LSM:Register("sound", "|cFFFF8000Moon|r", [[Interface\Addons\SharedMedia_Alerts\sound\Moon.ogg]]) 
LSM:Register("sound", "|cFFFF8000Move|r", [[Interface\Addons\SharedMedia_Alerts\sound\Move.ogg]]) 
LSM:Register("sound", "|cFFFF8000North|r", [[Interface\Addons\SharedMedia_Alerts\sound\North.ogg]]) 
LSM:Register("sound", "|cFFFF8000Nuke|r", [[Interface\Addons\SharedMedia_Alerts\sound\Nuke.ogg]]) 
LSM:Register("sound", "|cFFFF8000Orb|r", [[Interface\Addons\SharedMedia_Alerts\sound\Orb.ogg]]) 
LSM:Register("sound", "|cFFFF8000Orbs|r", [[Interface\Addons\SharedMedia_Alerts\sound\Orbs.ogg]]) 
LSM:Register("sound", "|cFFFF8000Out|r", [[Interface\Addons\SharedMedia_Alerts\sound\Out.ogg]]) 
LSM:Register("sound", "|cFFFF8000Overlap|r", [[Interface\Addons\SharedMedia_Alerts\sound\Overlap.ogg]]) 
LSM:Register("sound", "|cFFFF8000Phase 1|r", [[Interface\Addons\SharedMedia_Alerts\sound\Phase1.ogg]]) 
LSM:Register("sound", "|cFFFF8000Phase 2|r", [[Interface\Addons\SharedMedia_Alerts\sound\Phase2.ogg]]) 
LSM:Register("sound", "|cFFFF8000Phase 3|r", [[Interface\Addons\SharedMedia_Alerts\sound\Phase3.ogg]]) 
LSM:Register("sound", "|cFFFF8000Phase 4|r", [[Interface\Addons\SharedMedia_Alerts\sound\Phase4.ogg]]) 
LSM:Register("sound", "|cFFFF8000Phase 5|r", [[Interface\Addons\SharedMedia_Alerts\sound\Phase5.ogg]]) 
LSM:Register("sound", "|cFFFF8000Poison|r", [[Interface\Addons\SharedMedia_Alerts\sound\Poison.ogg]]) 
LSM:Register("sound", "|cFFFF8000Portal|r", [[Interface\Addons\SharedMedia_Alerts\sound\Portal.ogg]]) 
LSM:Register("sound", "|cFFFF8000Potion|r", [[Interface\Addons\SharedMedia_Alerts\sound\Potion.ogg]]) 
LSM:Register("sound", "|cFFFF8000Pull|r", [[Interface\Addons\SharedMedia_Alerts\sound\Pull.ogg]]) 
LSM:Register("sound", "|cFFFF8000Push|r", [[Interface\Addons\SharedMedia_Alerts\sound\Push.ogg]]) 
LSM:Register("sound", "|cFFFF8000Range|r", [[Interface\Addons\SharedMedia_Alerts\sound\Range.ogg]]) 
LSM:Register("sound", "|cFFFF8000Ready|r", [[Interface\Addons\SharedMedia_Alerts\sound\Ready.ogg]]) 
LSM:Register("sound", "|cFFFF8000Reflect|r", [[Interface\Addons\SharedMedia_Alerts\sound\Reflect.ogg]]) 
LSM:Register("sound", "|cFFFF8000Refresh|r", [[Interface\Addons\SharedMedia_Alerts\sound\Refresh.ogg]]) 
LSM:Register("sound", "|cFFFF8000Release|r", [[Interface\Addons\SharedMedia_Alerts\sound\Release.ogg]]) 
LSM:Register("sound", "|cFFFF8000Right|r", [[Interface\Addons\SharedMedia_Alerts\sound\Right.ogg]]) 
LSM:Register("sound", "|cFFFF8000Root|r", [[Interface\Addons\SharedMedia_Alerts\sound\Root.ogg]]) 
LSM:Register("sound", "|cFFFF8000Run Away|r", [[Interface\Addons\SharedMedia_Alerts\sound\RunAway.ogg]]) 
LSM:Register("sound", "|cFFFF8000Self CD|r", [[Interface\Addons\SharedMedia_Alerts\sound\SelfCD.ogg]]) 
LSM:Register("sound", "|cFFFF8000Shield|r", [[Interface\Addons\SharedMedia_Alerts\sound\Shield.ogg]]) 
LSM:Register("sound", "|cFFFF8000Skull|r", [[Interface\Addons\SharedMedia_Alerts\sound\Skull.ogg]]) 
LSM:Register("sound", "|cFFFF8000Slow|r", [[Interface\Addons\SharedMedia_Alerts\sound\Slow.ogg]]) 
LSM:Register("sound", "|cFFFF8000Soak|r", [[Interface\Addons\SharedMedia_Alerts\sound\Soak.ogg]]) 
LSM:Register("sound", "|cFFFF8000Soon|r", [[Interface\Addons\SharedMedia_Alerts\sound\Soon.ogg]]) 
LSM:Register("sound", "|cFFFF8000South|r", [[Interface\Addons\SharedMedia_Alerts\sound\South.ogg]]) 
LSM:Register("sound", "|cFFFF8000Spawn|r", [[Interface\Addons\SharedMedia_Alerts\sound\Spawn.ogg]]) 
LSM:Register("sound", "|cFFFF8000Spellsteal|r", [[Interface\Addons\SharedMedia_Alerts\sound\Spellsteal.ogg]]) 
LSM:Register("sound", "|cFFFF8000Split|r", [[Interface\Addons\SharedMedia_Alerts\sound\Split.ogg]]) 
LSM:Register("sound", "|cFFFF8000Spread|r", [[Interface\Addons\SharedMedia_Alerts\sound\Spread.ogg]]) 
LSM:Register("sound", "|cFFFF8000Square|r", [[Interface\Addons\SharedMedia_Alerts\sound\Square.ogg]]) 
LSM:Register("sound", "|cFFFF8000Stack|r", [[Interface\Addons\SharedMedia_Alerts\sound\Stack.ogg]]) 
LSM:Register("sound", "|cFFFF8000Star|r", [[Interface\Addons\SharedMedia_Alerts\sound\Star.ogg]]) 
LSM:Register("sound", "|cFFFF8000Stop|r", [[Interface\Addons\SharedMedia_Alerts\sound\Stop.ogg]]) 
LSM:Register("sound", "|cFFFF8000Stop Cast|r", [[Interface\Addons\SharedMedia_Alerts\sound\StopCast.ogg]]) 
LSM:Register("sound", "|cFFFF8000Stun|r", [[Interface\Addons\SharedMedia_Alerts\sound\Stun.ogg]]) 
LSM:Register("sound", "|cFFFF8000Switch|r", [[Interface\Addons\SharedMedia_Alerts\sound\Switch.ogg]]) 
LSM:Register("sound", "|cFFFF8000Tank Buster|r", [[Interface\Addons\SharedMedia_Alerts\sound\TankBuster.ogg]]) 
LSM:Register("sound", "|cFFFF8000Tank CD|r", [[Interface\Addons\SharedMedia_Alerts\sound\TankCD.ogg]]) 
LSM:Register("sound", "|cFFFF8000Tank Frontal|r", [[Interface\Addons\SharedMedia_Alerts\sound\TankFrontal.ogg]]) 
LSM:Register("sound", "|cFFFF8000Targeted|r", [[Interface\Addons\SharedMedia_Alerts\sound\Targeted.ogg]]) 
LSM:Register("sound", "|cFFFF8000Taunt|r", [[Interface\Addons\SharedMedia_Alerts\sound\Taunt.ogg]]) 
LSM:Register("sound", "|cFFFF8000Top|r", [[Interface\Addons\SharedMedia_Alerts\sound\Top.ogg]]) 
LSM:Register("sound", "|cFFFF8000Totem|r", [[Interface\Addons\SharedMedia_Alerts\sound\Totem.ogg]]) 
LSM:Register("sound", "|cFFFF8000Transition|r", [[Interface\Addons\SharedMedia_Alerts\sound\Transition.ogg]]) 
LSM:Register("sound", "|cFFFF8000Trap|r", [[Interface\Addons\SharedMedia_Alerts\sound\Trap.ogg]]) 
LSM:Register("sound", "|cFFFF8000Triangle|r", [[Interface\Addons\SharedMedia_Alerts\sound\Triangle.ogg]]) 
LSM:Register("sound", "|cFFFF8000Trinket|r", [[Interface\Addons\SharedMedia_Alerts\sound\Trinket.ogg]]) 
LSM:Register("sound", "|cFFFF8000Turn|r", [[Interface\Addons\SharedMedia_Alerts\sound\Turn.ogg]]) 
LSM:Register("sound", "|cFFFF8000Up|r", [[Interface\Addons\SharedMedia_Alerts\sound\Up.ogg]]) 
LSM:Register("sound", "|cFFFF8000Use|r", [[Interface\Addons\SharedMedia_Alerts\sound\Use.ogg]]) 
LSM:Register("sound", "|cFFFF8000Utility|r", [[Interface\Addons\SharedMedia_Alerts\sound\Utility.ogg]]) 
LSM:Register("sound", "|cFFFF8000West|r", [[Interface\Addons\SharedMedia_Alerts\sound\West.ogg]]) 

-- -----
--   STATUSBAR
-- -----
